node {
	stage "pull"
    git url: 'https://github.com/vgalloy/server.git'

	stage "clean"
    sh "mvn clean"

	stage "checkstyle"
    sh "mvn checkstyle:check"

	stage "pmd"
    sh "mvn pmd:pmd"

	stage "findbugs"
    sh "mvn findbugs:check"

	stage "resources"
    sh "mvn resources:resources"

	stage "compile"
    sh "mvn compiler:compile"

	stage "testResources"
    sh "mvn resources:testResources"

	stage "testCompile"
    sh "mvn compiler:testCompile"

	stage "test"
    sh "mvn surefire:test"

	stage "package"
    sh "mvn jar:jar spring-boot:repackage"
}